version: '2'
services:
  web:
    image: buig/sf-php8.0-apache
    container_name: fantasyF1
    volumes:
      - .:/code:rw
      - ./provisioning/sites-enabled:/etc/apache2/sites-enabled
    env_file:
      - .env.webapp
    ports:
      - "8085:80"
    networks:
      - edu-shared
    tty: true

networks:
  edu-shared:
    external: true
